# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awstestmodel',
            name='new_field',
            field=models.CharField(default='some more data', max_length=600),
        ),
    ]
